# Generated by Django 3.1.8 on 2022-06-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='user',
            new_name='accountName',
        ),
    ]
