# Generated by Django 3.1.8 on 2022-06-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220630_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='accountName',
            new_name='user',
        ),
    ]
